name: Deployment
on:
  push:
    branches: [ prod ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Cleanup & build
        run: |
          cd $HOME/homepage
          git checkout prod
          git pull origin prod --rebase
          git stash pop
          docker compose down --remove-orphans
          docker compose build --pull --progress plain
      - name: Deploy
        run: |
          cd $HOME/homepage
          docker compose up -d --quiet-pull --remove-orphans
